### ISSUE TITLE
`py.test` is no longer provided by pytest since 7.2.0

### ISSUE THREAD

**Issue by frenzymadness** [alfredodeza/tambo#12]
https://github.com/alfredodeza/tambo/blob/6a2b08f0bbc798d13c8754b1231d81a967459314/tambo/tests/test_parser.py#L1

**Comment by ktdreyer** [comment]
Thanks, I've submitted [your Fedora patch](https://src.fedoraproject.org/rpms/python-tambo/pull-request/2) at https://github.com/alfredodeza/tambo/pull/13
