### ISSUE TITLE
add full MIT license text

### ISSUE THREAD

**Issue by ktdreyer** [alfredodeza/tambo#6]
In terms of packaging this module for Fedora, the Fedora Packaging Guidelines suggest that I ask you to include a LICENSE file in the root of the project. By including a copy of the exact MIT license text, you will make the terms of the tambo license very clear.

Also, in the specific case of tambo's MIT license, all derivative copies of tambo are required to contain the disclaimer text within the MIT license (as described in the sentence "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.") So in order to ease development and distribution of tambo, it makes sense to simply include this text in the upstream project.

More details about this can be found on Fedora's wiki, under the "License Text" section: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text

Would you mind adding this LICENSE file with the MIT license text to the git repo and the module's MANIFEST.in?

**Comment by alfredodeza** [comment]
Added LICENSE and included in the MANIFEST.in in commit 34389cd
